version: '3.9'

services:
  postgres:
    image: postgres:16.2
    container_name: dsa-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    name: my_network
    driver: bridge
